language: node_js
node_js:
  - "4.3.1"
  - "0.10"
script: make test-coverage
# after_success:
#   - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
after_success:
  - './node_modules/.bin/codeclimate-test-reporter < ./coverage/lcov.info'
addons:
  code_climate:
    repo_token: f2514f5d0dd03f5a2db801aa0f07483b7ad65a0a3041ff4cf543c93a5ece5456
